version: '3.8'

services:
  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    container_name: seucantinho-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/seucantinho
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:15
    container_name: seucantinho-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seucantinho
    ports:
      - "5433:5432"

