spring:
  datasource:
    url: jdbc:postgresql://seucantinho-db:5432/seucantinho
    username: seucantinho_user
    password: cantinho_secreto
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update

server:
  port: 8080

logging:
  level:
    com.seucantinho: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

